export { default as LinkedinIco } from "./linkedin-icon"
export { default as CheckIco } from "./checkIcon"
export { default as DownloadIco } from "./downloadIcon"
export { default as RedirectIco } from "./redirectIcon"
export { default as SendEmailIco } from "./sendEmailIcon"
export { default as MenuIco } from "./menuIcon"
export { default as XIco } from "./xIcon"